# Generated by Django 3.2 on 2024-03-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_alter_appeal_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='uid',
        ),
    ]
